# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 06:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('sub_sector', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('prediction', models.FloatField()),
                ('errorMargin', models.FloatField()),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'assetData',
            },
        ),
        migrations.CreateModel(
            name='MinimumSpanningTreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetIdTwo', models.IntegerField()),
                ('slope', models.FloatField()),
                ('intercept', models.FloatField()),
                ('assetIdOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'minimumSpanningTreeModel',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('headline', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effect', models.FloatField()),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'newsGroup',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAssetMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentCount', models.IntegerField()),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'portfolioAssetMapping',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('trade', models.CharField(max_length=50)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
                ('mappingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PortfolioAssetMapping')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coefficients', django.contrib.postgres.fields.jsonb.JSONField()),
                ('AssetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'timeSeriesModel',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('trade', models.CharField(max_length=50)),
                ('initialCount', models.IntegerField()),
                ('finalCount', models.IntegerField()),
                ('tradeCount', models.IntegerField()),
                ('price', models.FloatField()),
                ('mappingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PortfolioAssetMapping')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='portfolioassetmapping',
            name='portfolioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Portfolio'),
        ),
        migrations.AddField(
            model_name='news',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NewsGroup'),
        ),
    ]
