# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161017_1155'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeseriesmodel',
            table='time_series_model',
        ),
    ]
