# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161006_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='sub_sector',
            new_name='subSector',
        ),
    ]
