# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161019_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='prediction',
            field=models.FloatField(default=0.0),
        ),
    ]
