# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161012_1156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetdata',
            table='assetdata',
        ),
    ]
