# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161012_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdata',
            old_name='assetId',
            new_name='asset',
        ),
    ]
