# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161020_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='RippleEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            options={
                'db_table': 'ripple_effect',
            },
        ),
    ]
