# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161012_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioassetmapping',
            old_name='assetId',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='portfolioassetmapping',
            old_name='portfolioId',
            new_name='portfolio',
        ),
    ]
