# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161012_1603'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolioassetmapping',
            table='portfolio_asset_mapping',
        ),
    ]
