# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rippleeffect'),
        ('app', '0007_auto_20161020_0850'),
    ]

    operations = [
    ]
