# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161012_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mappingId',
            new_name='mapping',
        ),
    ]
