# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161020_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsgroup',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='news',
            name='group',
        ),
        migrations.AddField(
            model_name='news',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='NewsGroup',
        ),
    ]
