# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161013_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='minimumspanningtreemodel',
            table='minimum_spanning_tree_model',
        ),
        migrations.AlterModelTable(
            name='newsgroup',
            table='news_group',
        ),
        migrations.AlterModelTable(
            name='timeseriesmodel',
            table='timeSeries_model',
        ),
    ]
