# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161013_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mapping',
            new_name='mappingId',
        ),
        migrations.AlterModelTable(
            name='minimumspanningtreemodel',
            table='minimumSpanningTreeModel',
        ),
        migrations.AlterModelTable(
            name='newsgroup',
            table='newsGroup',
        ),
        migrations.AlterModelTable(
            name='timeseriesmodel',
            table='timeSeriesModel',
        ),
    ]
