# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161013_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='mappingId',
            new_name='mapping',
        ),
        migrations.RenameField(
            model_name='timeseriesmodel',
            old_name='AssetId',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='timeseriesmodel',
            old_name='Coefficients',
            new_name='coefficients',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='mappingId',
            new_name='mapping',
        ),
        migrations.AlterModelTable(
            name='minimumspanningtreemodel',
            table='minimum_spanning_tree_model',
        ),
        migrations.AlterModelTable(
            name='newsgroup',
            table='news_group',
        ),
        migrations.AlterModelTable(
            name='timeseriesmodel',
            table='timeSeries_model',
        ),
    ]
