# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161013_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='groupId',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='assetId',
            new_name='asset',
        ),
    ]
