# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_news_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effect', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='assetdata',
            name='netEffect',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
