# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161013_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='asset',
            new_name='recommendedAsset',
        ),
    ]
