# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161024_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdata',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
