# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161014_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdata',
            old_name='timestamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='timestamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
