# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161025_0730'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsgroup',
            table='news_group',
        ),
    ]
