# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20161025_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.NewsGroup'),
            preserve_default=False,
        ),
    ]
