# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_news_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='group',
        ),
    ]
