# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_news_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rippleeffect',
            old_name='asset',
            new_name='assetIdOne',
        ),
        migrations.AddField(
            model_name='rippleeffect',
            name='assetIdTwo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rippleeffect',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
