# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161025_0724'),
        ('app', '0019_remove_news_group'),
    ]

    operations = [
    ]
