# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20161103_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
